[
  {
    domain: '101',
    id_1: 'A1',
    name_1: '出席',
    assessOption_1: 'C',
    id_2: 'A2',
    name_2: '准时',
    assessOption_2: 'B',
    id_3: 'A3',
    name_3: '保持个人卫生的习惯',
    assessOption_3: 'B',
    id_4: 'A4',
    name_4: '无习惯性动作或语言',
    assessOption_4: 'D',
  },
  {
    domain: '101',
    id_1: 'A5',
    name_1: '礼貌',
    assessOption_1: 'D',
    id_2: 'A6',
    name_2: '愉快',
    assessOption_2: 'C',
    id_3: 'A7',
    name_3: '诚实',
    assessOption_3: 'B',
    id_4: 'A8',
    name_4: '友善',
    assessOption_4: 'A',
  },
  {
    domain: '101',
    id_1: 'A9',
    name_1: '动机',
    assessOption_1: 'D',
    id_2: 'A10',
    name_2: '努力',
    assessOption_2: 'A',
    id_3: 'A27',
    name_3: '小组合作',
    assessOption_3: 'B',
    id_4: 'A28',
    name_4: '与上司合作',
    assessOption_4: 'D',
  },
  {
    domain: '101',
    id_1: 'A29',
    name_1: '工作品质',
    assessOption_1: 'B',
    id_2: 'A30',
    name_2: '按时完成工作',
    assessOption_2: 'C',
    id_3: 'A31',
    name_3: '自我批评',
    assessOption_3: 'C',
    id_4: 'A32',
    name_4: '请求协助',
    assessOption_4: 'A',
  },
  {
    domain: '101',
    id_1: 'A33',
    name_1: '安全习惯',
    assessOption_1: 'D',
    id_2: 'A34',
    name_2: '收拾的习惯',
    assessOption_2: 'C',
  },
  {
    domain: '102',
    id_1: 'B1',
    name_1: '工作姿势-站立',
    assessOption_1: 'C',
    id_2: 'B2',
    name_2: '工作姿势-走动',
    assessOption_2: 'D',
    id_3: 'B3',
    name_3: '工作姿势-跑',
    assessOption_3: 'C',
    id_4: 'B4',
    name_4: '工作姿势-跨（跳）',
    assessOption_4: 'B',
  },
  {
    domain: '102',
    id_1: 'B5',
    name_1: '工作姿势-蹲',
    assessOption_1: 'C',
    id_2: 'B6',
    name_2: '工作姿势-跪',
    assessOption_2: 'A',
    id_3: 'B7',
    name_3: '工作姿势-坐',
    assessOption_3: 'B',
    id_4: 'B8',
    name_4: '工作姿势-爬',
    assessOption_4: 'B',
  },
  {
    domain: '102',
    id_1: 'B9',
    name_1: '工作姿势-躺',
    assessOption_1: 'B',
    id_2: 'B10',
    name_2: '工作姿势-弯腰',
    assessOption_2: 'C',
    id_3: 'B25',
    name_3: '感官知觉-大小辨别',
    assessOption_3: 'A',
    id_4: 'B26',
    name_4: '感官知觉-色彩辨别',
    assessOption_4: 'A',
  },
  {
    domain: '102',
    id_1: 'B27',
    name_1: '感官知觉-空间知觉',
    assessOption_1: 'D',
    id_2: 'B28',
    name_2: '感官知觉-触觉',
    assessOption_2: 'A',
    id_3: 'B29',
    name_3: '感官知觉-听辨力',
    assessOption_3: 'D',
    id_4: 'B30',
    name_4: '感官知觉-听力',
    assessOption_4: 'A',
  },
  {
    domain: '102',
    id_1: 'B31',
    name_1: '感官知觉-嗅味觉',
    assessOption_1: 'A',
    id_2: 'B32',
    name_2: '协调能力-手眼协调',
    assessOption_2: 'A',
    id_3: 'B33',
    name_3: '协调能力-手脚协调',
    assessOption_3: 'C',
    id_4: 'B34',
    name_4: '协调能力-手眼脚协调',
    assessOption_4: 'A',
  },
  {
    domain: '102',
    id_1: 'B35',
    name_1: '应付工作的足够体力',
    assessOption_1: 'C',
    id_2: 'B36',
    name_2: '记住指示',
    assessOption_2: 'B',
  },
  {
    domain: '103',
    id_1: 'C1',
    name_1: '家庭维持-烹饪的能力',
    assessOption_1: 'A',
    id_2: 'C2',
    name_2: '家庭维持-家居的能力',
    assessOption_2: 'A',
    id_3: 'C3',
    name_3: '家庭维持-家居安全',
    assessOption_3: 'A',
    id_4: 'C4',
    name_4: '金钱的管理-收入的计算',
    assessOption_4: 'D',
  },
  {
    domain: '103',
    id_1: 'C5',
    name_1: '金钱的管理-预算及支出',
    assessOption_1: 'A',
    id_2: 'C6',
    name_2: '金钱的管理-借贷',
    assessOption_2: 'A',
    id_3: 'C7',
    name_3: '金钱的管理-储蓄',
    assessOption_3: 'C',
    id_4: 'C8',
    name_4: '金钱的管理-纳税',
    assessOption_4: 'A',
  },
  {
    domain: '103',
    id_1: 'C9',
    name_1: '个人卫生与保健-涣洗与整饰',
    assessOption_1: 'C',
    id_2: 'C10',
    name_2: '个人卫生与保健-身心保健',
    assessOption_2: 'A',
    id_3: 'C11',
    name_3: '个人卫生与保健-疾病医疗',
    assessOption_3: 'B',
    id_4: 'C12',
    name_4: '休闲生活-休闲资源的使用',
    assessOption_4: 'A',
  },
  {
    domain: '103',
    id_1: 'C13',
    name_1: '休闲生活-参与社区活动',
    assessOption_1: 'C',
    id_2: 'C14',
    name_2: '休闲生活-活动安排的能力',
    assessOption_2: 'D',
    id_3: 'C15',
    name_3: '休闲生活-旅行能力',
    assessOption_3: 'C',
    id_4: 'C16',
    name_4: '购物与消费-购物场所',
    assessOption_4: 'A',
  },
  {
    domain: '103',
    id_1: 'C17',
    name_1: '购物与消费-购物物品',
    assessOption_1: 'C',
    id_2: 'C18',
    name_2: '购物与消费-购物手续',
    assessOption_2: 'B',
    id_3: 'C19',
    name_3: '社交能力-家居礼仪',
    assessOption_3: 'B',
    id_4: 'C20',
    name_4: '社交能力-睦邻',
    assessOption_4: 'C',
  },
];
